#!/usr/bin/env python3
#
# Copyright      2022  Xiaomi Corp.        (authors: Fangjun Kuang)
#
# See LICENSE for clarification regarding multiple authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
examples = [
    [
        "Chinese+English",
        "csukuangfj/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/tal_csasr/0.wav",
    ],
    [
        "Chinese+English+Cantonese",
        "csukuangfj/sherpa-onnx-paraformer-trilingual-zh-cantonese-en",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/cantonese/2.wav",
    ],
    [
        "Chinese+English+Cantonese+Japanese+Korean",
        "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/sense_voice/yue.wav",
    ],
    [
        "Cantonese",
        "zrjin/icefall-asr-mdcc-zipformer-2024-03-11",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/cantonese/1.wav",
    ],
    [
        "English",
        "whisper-base.en",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/librispeech/1089-134686-0001.wav",
    ],
    [
        "Chinese",
        "csukuangfj/sherpa-onnx-paraformer-zh-2024-03-09",
        "greedy_search",
        4,
        "Yes",
        "./test_wavs/paraformer-zh/四川话.wav",
    ],
    [
        "Japanese",
        "reazon-research/reazonspeech-k2-v2",
        "greedy_search",
        4,
        "No",
        "./test_wavs/japanese/1.wav",
    ],
    [
        "Korean",
        "k2-fsa/sherpa-onnx-zipformer-korean-2024-06-24",
        "greedy_search",
        4,
        "No",
        "./test_wavs/korean/0.wav",
    ],
    [
        "Russian",
        "csukuangfj/sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24",
        "greedy_search",
        4,
        "No",
        "./test_wavs/russian/russian-i-love-you.wav",
    ],
    [
        "Thai",
        "yfyeung/icefall-asr-gigaspeech2-th-zipformer-2024-06-20",
        "greedy_search",
        4,
        "No",
        "./test_wavs/thai/0.wav",
    ],
    #  [
    #      "Russian",
    #      "alphacep/vosk-model-ru",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/russian/test.wav",
    #  ],
    #  [
    #      "German",
    #      "csukuangfj/wav2vec2.0-torchaudio",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/german/20170517-0900-PLENARY-16-de_20170517.wav",
    #  ],
    #  [
    #      "Arabic",
    #      "AmirHussein/icefall-asr-mgb2-conformer_ctc-2022-27-06",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/arabic/a.wav",
    #  ],
    #  [
    #      "Tibetan",
    #      "syzym/icefall-asr-xbmu-amdo31-pruned-transducer-stateless7-2022-12-02",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/tibetan/a_0_cacm-A70_31117.wav",
    #  ],
    #  [
    #      "French",
    #      "shaojieli/sherpa-onnx-streaming-zipformer-fr-2023-04-14",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/french/common_voice_fr_19364697.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "desh2608/icefall-asr-alimeeting-pruned-transducer-stateless7",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/alimeeting/R8003_M8001-8004-165.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "csukuangfj/sherpa-onnx-paraformer-zh-2024-03-09",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/paraformer-zh/天津话.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "csukuangfj/sherpa-onnx-paraformer-zh-2024-03-09",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/paraformer-zh/郑州话.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "desh2608/icefall-asr-alimeeting-pruned-transducer-stateless7",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/alimeeting/R8008_M8013-8049-74.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "desh2608/icefall-asr-alimeeting-pruned-transducer-stateless7",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/alimeeting/R8009_M8020_N_SPK8026-8026-209.wav",
    #  ],
    #  [
    #      "English",
    #      "videodanchik/icefall-asr-tedlium3-conformer-ctc2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tedlium3/DanBarber_2010-219.wav",
    #  ],
    #  [
    #      "English",
    #      "whisper-base.en",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tedlium3/DanielKahneman_2010-157.wav",
    #  ],
    #  [
    #      "English",
    #      "videodanchik/icefall-asr-tedlium3-conformer-ctc2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tedlium3/RobertGupta_2010U-15.wav",
    #  ],
    #  # librispeech
    #  # https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless5-2022-05-13/tree/main/test_wavs
    #  [
    #      "English",
    #      "csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/librispeech/1089-134686-0001.wav",
    #  ],
    #  [
    #      "English",
    #      "csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/librispeech/1221-135766-0001.wav",
    #  ],
    #  [
    #      "English",
    #      "csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/librispeech/1221-135766-0002.wav",
    #  ],
    #  # gigaspeech
    #  [
    #      "English",
    #      "wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/gigaspeech/1-minute-audiobook.opus",
    #  ],
    #  [
    #      "English",
    #      "wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/gigaspeech/100-seconds-podcast.opus",
    #  ],
    #  [
    #      "English",
    #      "wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/gigaspeech/100-seconds-youtube.opus",
    #  ],
    #  # wenetspeech
    #  # https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless2/tree/main/test_wavs
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/wenetspeech/DEV_T0000000000.opus",
    #  ],
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/wenetspeech/DEV_T0000000001.opus",
    #  ],
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/wenetspeech/DEV_T0000000002.opus",
    #  ],
    #  # aishell2-A
    #  # https://huggingface.co/yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-A-2022-07-12/tree/main/test_wavs
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-A-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0030.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-A-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0162.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-A-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0215.wav",
    #  ],
    #  # aishell2-B
    #  # https://huggingface.co/yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-A-2022-07-12/tree/main/test_wavs
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-B-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0030.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-B-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0162.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "yuekai/icefall-asr-aishell2-pruned-transducer-stateless5-B-2022-07-12",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aishell2/ID0012W0215.wav",
    #  ],
    #  # aishell2-B
    #  # https://huggingface.co/luomingshuang/icefall_asr_aidatatang-200zh_pruned_transducer_stateless2/tree/main/test_wavs
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_aidatatang-200zh_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aidatatang_200zh/T0055G0036S0002.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_aidatatang-200zh_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aidatatang_200zh/T0055G0036S0003.wav",
    #  ],
    #  [
    #      "Chinese",
    #      "luomingshuang/icefall_asr_aidatatang-200zh_pruned_transducer_stateless2",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/aidatatang_200zh/T0055G0036S0004.wav",
    #  ],
    #  # tal_csasr
    #  [
    #      "Chinese+English",
    #      "ptrnull/icefall-asr-conv-emformer-transducer-stateless2-zh",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tal_csasr/210_36476_210_8341_1_1533271973_7057520_132.wav",
    #  ],
    #  [
    #      "Chinese+English",
    #      "ptrnull/icefall-asr-conv-emformer-transducer-stateless2-zh",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tal_csasr/210_36476_210_8341_1_1533271973_7057520_138.wav",
    #  ],
    #  [
    #      "Chinese+English",
    #      "ptrnull/icefall-asr-conv-emformer-transducer-stateless2-zh",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/tal_csasr/210_36476_210_8341_1_1533271973_7057520_145.wav",
    #  ],
    #  [
    #      "Tibetan",
    #      "syzym/icefall-asr-xbmu-amdo31-pruned-transducer-stateless7-2022-12-02",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/tibetan/a_0_cacm-A70_31116.wav",
    #  ],
    #  [
    #      "Tibetan",
    #      "syzym/icefall-asr-xbmu-amdo31-pruned-transducer-stateless7-2022-12-02",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/tibetan/a_0_cacm-A70_31118.wav",
    #  ],
    #  # arabic
    #  [
    #      "Arabic",
    #      "AmirHussein/icefall-asr-mgb2-conformer_ctc-2022-27-06",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/arabic/b.wav",
    #  ],
    #  [
    #      "Arabic",
    #      "AmirHussein/icefall-asr-mgb2-conformer_ctc-2022-27-06",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/arabic/c.wav",
    #  ],
    #  [
    #      "German",
    #      "csukuangfj/wav2vec2.0-torchaudio",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/german/20120315-0900-PLENARY-14-de_20120315.wav",
    #  ],
    #  [
    #      "French",
    #      "shaojieli/sherpa-onnx-streaming-zipformer-fr-2023-04-14",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/french/common_voice_fr_19738183.wav",
    #  ],
    #  [
    #      "French",
    #      "shaojieli/sherpa-onnx-streaming-zipformer-fr-2023-04-14",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/french/common_voice_fr_27024649.wav",
    #  ],
    #  [
    #      "Korean",
    #      "k2-fsa/sherpa-onnx-zipformer-korean-2024-06-24",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/korean/1.wav",
    #  ],
    #  [
    #      "Korean",
    #      "k2-fsa/sherpa-onnx-zipformer-korean-2024-06-24",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/korean/2.wav",
    #  ],
    #  [
    #      "Korean",
    #      "k2-fsa/sherpa-onnx-zipformer-korean-2024-06-24",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/korean/3.wav",
    #  ],
    #  [
    #      "Thai",
    #      "yfyeung/icefall-asr-gigaspeech2-th-zipformer-2024-06-20",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/thai/1.wav",
    #  ],
    #  [
    #      "Thai",
    #      "yfyeung/icefall-asr-gigaspeech2-th-zipformer-2024-06-20",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/thai/2.wav",
    #  ],
    #  [
    #      "Chinese+English+Cantonese+Japanese+Korean",
    #      "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/sense_voice/zh.wav",
    #  ],
    #  [
    #      "Chinese+English+Cantonese+Japanese+Korean",
    #      "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/sense_voice/en.wav",
    #  ],
    #  [
    #      "Chinese+English+Cantonese+Japanese+Korean",
    #      "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/sense_voice/ja.wav",
    #  ],
    #  [
    #      "Chinese+English+Cantonese+Japanese+Korean",
    #      "csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17",
    #      "greedy_search",
    #      4,
    #      "Yes",
    #      "./test_wavs/sense_voice/ko.wav",
    #  ],
    #  [
    #      "Japanese",
    #      "reazon-research/reazonspeech-k2-v2",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/japanese/2.wav",
    #  ],
    #  [
    #      "Japanese",
    #      "reazon-research/reazonspeech-k2-v2",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/japanese/3.wav",
    #  ],
    #  [
    #      "Japanese",
    #      "reazon-research/reazonspeech-k2-v2",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/japanese/4.wav",
    #  ],
    #  [
    #      "Japanese",
    #      "reazon-research/reazonspeech-k2-v2",
    #      "greedy_search",
    #      4,
    #      "No",
    #      "./test_wavs/japanese/5.wav",
    #  ],
]
